// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {theme} from '../models';

export function GetBootstrap():Promise<main.Bootstrap>;

export function Quit():Promise<void>;

export function SetAlwaysOnTop(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<theme.Theme>;
